### PR TITLE
👌 IMPROVE: Add footnote translations

### PR DESCRIPTION
**Pull request by chrisjsewell**
Fixes https://github.com/executablebooks/jupyter-book/issues/223#issuecomment-762478301

e.g. for `language = "fr"`

image

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Hi @pnavaro how's this for the footer text?
As you can see from the screenshot above, `By`, `Copyright` and `Last updated on` are translated

**Comment by chrisjsewell** [comment]
On a side note @choldgraf, when I try to build the docs locally (with `tox -e docs-clean`) I get:

```
checking consistency... /Users/chrisjsewell/Documents/GitHub/sphinx-book-theme/docs/reference/blog/post1.md: WARNING: document isn't included in any toctree
/Users/chrisjsewell/Documents/GitHub/sphinx-book-theme/docs/reference/blog/post2.md: WARNING: document isn't included in any toctree
```

which is "fixed" if I add `blogpost: true` to those documents front-matter.

weirdly this does not happen when building here on RTD, perhaps some issue with how the relative paths are resolved for `blog_post_pattern = "reference/blog/*.md"`

**Comment by chrisjsewell** [comment]
>  perhaps some issue with how the relative paths are resolved for `blog_post_pattern = "reference/blog/*.md"`

https://github.com/sunpy/ablog/pull/89

**Comment by pnavaro** [comment]
> Hi @pnavaro how's this for the footer text?
> As you can see from the screenshot above, `By`, `Copyright` and `Last updated on` are translated

It does not work for me, everything is well translated in french except the footer. Perhaps it is my installation that is not correct:
```
Name: jupyter-book
Version: 0.9.1
Name: sphinx-book-theme
Version: 0.0.39
```

**Comment by chrisjsewell** [comment]
Oh this is not released yet it's just in this PR at present

**Comment by pnavaro** [comment]
> Oh this is not released yet it's just in this PR at present

Ah OK 😅. Merci!

**Pull request merged**
