### PR TITLE
add support for gitlab issue button

### PR DESCRIPTION
**Pull request by akhmerov**
Source for confirming that the format is correct: https://docs.gitlab.com/ee/user/project/issues/create_issues.html#using-a-url-with-prefilled-values

### CODE REVIEW

**Comment by akhmerov** [comment]
I don't understand the CI failures, and [the testing guide](https://sphinx-book-theme.readthedocs.io/en/stable/contributing/tests.html) doesn't quite help. Also it seems that tox tests are way behind NEP 29.

**Comment by akhmerov** [comment]
Lighthouse failure seems unrelated, the rest of the tests are passing.

**Comment by akhmerov** [comment]
I've updated the test, however I can't figure out how to update the reference html files. Do you have any pointers?

**Comment by akhmerov** [comment]
Should be ready now.

**Comment by akhmerov** [comment]
@choldgraf I saw you're bumping versions in the repo. This PR should be rather straightforward and it's ready to merge :pray: :eyes:

**Review by choldgraf — APPROVED** [review]
Looks good to me - thanks for the ping!

**Comment by houqp** [comment]
hi, any plan to cut a new release to include this feature?

**Pull request merged**
