### PR TITLE
🐛 FOX: Issue with squashed content w/ left ToC on mobile

### PR DESCRIPTION
**Pull request by DrDrij**
Potential fix for[ Issue with Left ToC and mobile (e.g. jupyter-book gallery) #303](https://github.com/executablebooks/sphinx-book-theme/issues/303).

Simply changes the hook on class `.bd-sidebar` with `#site-navigation` to override bootstrap css causing layout issue seen on <768px window on `https://executablebooks.org/`.

### CODE REVIEW

**Comment by choldgraf** [comment]
This seems good to me - were you able to find a page in the sphinx book theme that we could use as a test case? Otherwise perhaps we just merge and deploy, and see if this fixes the bug.

**Comment by chrisjsewell** [comment]
> Otherwise perhaps we just merge and deploy, and see if this fixes the bug.

maybe hold off for some extra testing also of #306

**Comment by DrDrij** [comment]
@choldgraf I have created a local version of `https://executablebooks.org/en/latest/gallery.html` and tested the latest `sphinx-book-theme` css file on it. It appears to have fixed the [squashed page issue](https://github.com/executablebooks/sphinx-book-theme/issues/303) caused by bootstrap styles taking priority over `sphinx-book-theme` styles. 🙂

image

**Comment by choldgraf** [comment]
Thanks for following up on this @DrDrij - perhaps we should merge this in and re-ping those issues to see if they still have the problem, it sounds like this will fix at least a subset of the issues

**Comment by choldgraf** [comment]
lol goddamnit, I called it FOX not FIX 🦊

**Pull request merged**
