### PR TITLE
📚 DOCS: Add sphinx-design and update docs a bit

### PR DESCRIPTION
**Pull request by choldgraf**
This is a small update to take some inspiration from sphinx-design's docs and play around with its directives etc. It updates our documentation to use sphinx-design a bit!

### CODE REVIEW

**Comment by chrisjsewell** [comment]
That sphinx design is pretty good isn’t it 😆 one extra think would be to use the logo svgs I created in figma

**Comment by choldgraf** [comment]
Ah good point - will update the logo to SVG when I'm back at the computer next

**Comment by chrisjsewell** [comment]
I updated the sphinx-design landing page a bit: https://sphinx-design.readthedocs.io/en/sbt-theme/, what do you reckon?

**Comment by choldgraf** [comment]
@chrisjsewell ah very cool! I guess that background is a feature flag in the grid directive now or something? Nice :-)

**Comment by choldgraf** [comment]
Latest push adds in SVG logos instead of PNGs (thanks for the Figma link btw, that is super useful). It also removes the title on the landing page, since "book theme" is already displayed to the left and I think this might be a bit less cluttered.

**Comment by choldgraf** [comment]
I think this is good to go - we can iterate from there. thanks @chrisjsewell for the sphinx-design improvements :-)

**Pull request merged**
