### PR TITLE
Updating topbar to be full width

### PR DESCRIPTION
**Pull request by choldgraf**
This is another test to see how the topbar looks at full width.

Here's a GIF:

6P9pXpHhz0

Compare that to current topbar:

image

### CODE REVIEW

**Comment by damianavila** [comment]
Mmm... I am not sure about this change... the left arrow has a "meaning" in the existing implementation and you are somehow losing that with this PR.

**Comment by choldgraf** [comment]
@damianavila ya, I kind of agree...I think we could add more things in the upper left and that might make it feel less awkward up there. But just to be clear: this PR isn't a "planned merge" it is just playing around with UX/UI

**Comment by damianavila** [comment]
> But just to be clear: this PR isn't a "planned merge" it is just playing around with UX/UI

Sure, my feedback was in that playing context...

**Comment by choldgraf** [comment]
cool - just wanted to make sure I wasn't confusing folks :-)

**Comment by pradyunsg** [comment]
We could move the sidebar collapse button to be attached to the side bar's content-side edge, instead of in the topbar?

**Comment by choldgraf** [comment]
@pradyunsg ya something like that might make sense, although then I feel like we are back to square one on the main reason I wanted to play around with this, which is that the top-left of the page is kind of "dead space" right now 🤔

**Comment by pradyunsg** [comment]
Status quo feels fine TBH. I'll probably spend some more time on sphinx-basic-ng this weekend, since that might make it easier to try things for us here.

**Comment by choldgraf** [comment]
Nice! Lemme know if you'd like a pair of 👀 on something in the NG theme

**Comment by choldgraf** [comment]
closing this one since it was mostly an experiment and it doesn't seem like there is a strong demand for a full-width topbar!

**Pull request closed without merging**
