### PR TITLE
BUG: fix for pydata-sphinx-theme>=0.13.3

### LINKED ISSUE #711: pydata-sphinx-theme 0.13.2 breaks sphinx-book-theme
### Describe the bug

After pydata-sphinx-theme updated to 0.13.2, our sphinx-build job in http://github.com/google/jax showed the following error:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 262, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/application.py", line 334, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 248, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 299, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/theming.py", line 232, in create
    self.load_extra_theme(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/theming.py", line 177, in load_extra_theme
    self.load_external_theme(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/theming.py", line 202, in load_external_theme
    self.app.registry.load_extension(self.app, entry_point.module)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/sphinx/registry.py", line 462, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname,
sphinx.errors.ExtensionError: Could not import extension sphinx_book_theme (exception: cannot import name '_get_theme_options' from 'pydata_sphinx_theme' (/home/docs/checkouts/readthedocs.org/user_builds/jax/envs/latest/lib/python3.9/site-packages/pydata_sphinx_theme/__init__.py))
```
We are pinning to `pydata-sphinx-theme==0.13.1` for the time being to fix the error.

- Our requirements file is here: https://github.com/google/jax/blob/main/docs/requirements.txt
- Our readthedocs config is here: https://github.com/google/jax/blob/main/.readthedocs.yml

The breaking change in pydata-sphinx-theme seems to be this one: https://github.com/pydata/pydata-sphinx-theme/commit/fc975d0737a6096dcadd783128027aa4469e7261

I'm reporting here because it looks like sphinx-book-theme is using an API that is intended to be private.

### PR DESCRIPTION
**Pull request by jakevdp**
Fixes #711  by pinning to pydata-sphinx-theme>=0.13.3 and using the new `pydata_sphinx_theme.utils` submodule

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @jakevdp for this PR. 

@AakashGfude this looks good to me but not overly familiar with the code base. Could you please review and this and organise a new release? Thanks.

**Comment by AakashGfude** [comment]
Thanks @jakevdp , this is awesome. I noticed a few UI issues which I have listed here: https://github.com/executablebooks/sphinx-book-theme/issues/715 .  I will merge this, fix them, and cut a release.

**Review by AakashGfude — APPROVED** [review]

**Comment by Saksham-13** [comment]
> Thanks @jakevdp , this is awesome. I noticed a few UI issues which I have listed here: #715 . I will merge this, fix them, and cut a release.

hey, by when will this be released?

**Comment by mauritsvanrees** [comment]
I confirm that version 1.0.1 fixes this.  Thanks!

**Comment by jakevdp** [comment]
Thanks all!

**Pull request merged**
