### PR TITLE
👌 IMPROVE: Consistent font size in navigation

### PR DESCRIPTION
**Pull request by pradyunsg**
Toward #144

### CODE REVIEW

**Comment by choldgraf** [comment]
I think this generally looks good. Though the sidebar feels a little bit cramped now that they're all the same size. I wonder what you think about slightly growing the vertical space between top-level left sidebar sections. So something like:

image

(which I added with this rule)

```css
ul.sidenav_l1 > li {
    margin-bottom: 0.2em;
}
```

**Comment by pradyunsg** [comment]
Definitely! Lemme wrap up dinner and I'll add the .2em to the elements. I *think* we already set margin/padding on li elements, so this should fit right in.

**Comment by pradyunsg** [comment]
Done!

**Comment by choldgraf** [comment]
nice - OK I'm gonna merge this, though perhaps these changes will also relate to the conversation in #160 and we can always iterate further

**Comment by choldgraf** [comment]
thanks @pradyunsg !! 🎉

**Pull request merged**
