### PR TITLE
🐛 FIX: checking for title in first page

### PR DESCRIPTION
**Pull request by choldgraf**
closes https://github.com/executablebooks/sphinx-book-theme/pull/190

### CODE REVIEW

**Comment by choldgraf** [comment]
FYI @chrisjsewell I haven't merged this because I can't figure out how to write the proper test for it. I may not have much time over the next few weeks to get to it. So I guess we could merge this in w/o a test but I'm hesitant to do so

**Comment by chrisjsewell** [comment]
Yeh no worries, I'll try to have a look at some point

**Comment by choldgraf** [comment]
Because another issue got opened that relates to this (https://github.com/executablebooks/jupyter-book/issues/966) I tried to another stab at it.

I've added a test that passes locally, but I can't figure out why it's not passing on here. (I'm not able to use nox yet because it's still freezing on me when I try to install it)

@chrisjsewell do you have any ideas?

**Comment by choldgraf** [comment]
ok got this working after changing our pytest fixture scope

**Pull request merged**
