### PR TITLE
Re-using Furo's reference documentation

### PR DESCRIPTION
**Pull request by choldgraf**

### CODE REVIEW

**Comment by damianavila** [comment]
From the description in the first post 😛 , it is not clear to me why you want to add Furo's reference docs here...

**Comment by chrisjsewell** [comment]
Yeh I'm not sure if this is the best approach 😬

**Comment by pradyunsg** [comment]
I believe the useful context is here: https://github.com/pradyunsg/furo/discussions/181

**Comment by choldgraf** [comment]
Yeah sorry for the lack on context. I left it in draft mode to try to avoid signaling that this needed review. I wanted something concrete to point to in the discussion in the furo docs that @pradyunsg linked to

**Pull request closed without merging**
