### PR TITLE
REMOVE: Theme-specific API styling to re-use PyData

### PR DESCRIPTION
**Pull request by choldgraf**
This drops our theme-specific API documentation (adapted from ReadTheDocs) and re-uses the pydata API style. The issues described in https://github.com/executablebooks/sphinx-book-theme/issues/307 had been resolved upstream, but apparently we were not re-using those styles here, and instead were over-writing them!

In that issue, they provided example code that created problematic API docs:

```
.. c:function:: dds_platform *dds_mpi(MPI_COMM comm, int sz)

.. py:function:: foo(a, b)
```

here's a comparison:

OLD:

NEW:

image

closes https://github.com/executablebooks/sphinx-book-theme/issues/307

### CODE REVIEW

**Comment by matteoaletti** [comment]
First of all, thank you for the great work.

For some reasons, I'd like to maintain the previous appearance of the documentation.
Do you think is it possible to somehow configure the theme to re-obtain the previous behavior?
Or is it simpler to pin the version of the theme to the 0.2 ?

**Comment by choldgraf** [comment]
Hmmm - you could certainly pin it, but you'd lose any new updates to the theme. Another option is to just copy all the CSS that was deleted in this PR, and add it as your own custom stylesheet

**Comment by matteoaletti** [comment]
Thank you for your answer.

I was able to solve my issue by adding the file as custom stylesheet.
I just had to do an intermediate step: I converted the "_autodoc.scss" file to a "custom.css" file. For this I have used a tool called scss-compile. I don't know if it was a good idea since I am not an expert of these kind of files, but for now it seems to work fine.
Thank you again.

**Comment by choldgraf** [comment]
yep that seems reasonable to me!

**Pull request merged**
