### PR TITLE
✨ IMPROVE: improve math styling

### LINKED ISSUE #345: Equation label misaligned
**Describe the bug**

Equation labels appear at a different height than the equations themselves

**To Reproduce**

1. Go to https://myst-parser.readthedocs.io/en/latest/using/syntax.html#equation-eqn-best
2. Observe the following alignment:

image

**Expected behavior**

Not a typesetting expert, but I think the label should have the same baseline.

**Environment**

Ubuntu + chrome & firefox (I observe problem on both)

**Additional context**

Not sure what's the best way to approach this, but adjusting `span.eqno` css seems appropriate.

### PR DESCRIPTION
**Pull request by akhmerov**
Closes #345, #272.

I didn't figure out how to set up the dev environment, so the compiled assets aren't updated. I hope CI picks it up.

---

Some motivation:

- #345 follows https://stackoverflow.com/a/42147108/2217463
- #272 is trickier:
  - There is no selector for an element that is followed by another one, only for a preceding one. That's why I apply a negative top margin to display math that follows a paragraph rather than remove the extra margin from a paragraph.
  - AFAIU 1.15rem margin-bottom of a paragraph seems to be inherited from bootstrap, so I can't use any variable for that.

### CODE REVIEW

**Comment by akhmerov** [comment]
Doesn't seem to work on either count :(

**Comment by choldgraf** [comment]
What was the sticking point for setting up the dev environment?

**Comment by akhmerov** [comment]
> What was the sticking point for setting up the dev environment?

Nothing I couldn't handle, just the sheer the amount of tools that I don't (yet) regularly use to install and learn, compared to the expected amount of changes (I incorrectly expected this to be an easy fix).

It was also not completely clear what it'd take—I'd need to install pre-commit to compile the assets, that would in turn install the EBP pre-commit hook, and that will bring in require some minification tools (?).

**Comment by choldgraf** [comment]
Are you going off of the instructions on the [contributing page](https://sphinx-book-theme.readthedocs.io/en/latest/contributing.html)?

I think the main thing is just to do:

```
pip install tox    (installs tox)
tox -e docs-update   (builds the documentation from the local copy)
```

that should be all you need to do. If you want pre-commit to run when you commit things, then also do:

```
pre-commit install
```

and it'll run from then on

**Comment by akhmerov** [comment]
Thanks, this worked, and helped me figure out the issues.

**Comment by akhmerov** [comment]
With modifications (here I added an equation without a label as a check):

---

image

---

Previously:

---

image

**Comment by choldgraf** [comment]
this looks great - thanks for improving this!

**Pull request merged**
