### PR TITLE
ENH: Add search field back to sidebar

### PR DESCRIPTION
**Pull request by choldgraf**
This makes minor CSS adjustments to fix some changes made in the latest pydata theme update.

Brief summary:

- Changes the default behavior of our search component. The **icon button** will show up on narrow screens, and the **search field button** will show up in the sidebar on wider screens.
- Re-applies the same primary/secondary colors to keep this consistent. It uses a slightly lighter color on dark mode to meet a11y contrast requirements (I used [this little tool for this](https://coolors.co/contrast-checker/176de8-ffffff)).
- De-saturates the background on dark mode (cc @Gouvernathor)
- Hides the "back to top" button on wide screens when the TOC of the page is present to avoid imposing it on the content.
- Standardizes the size of header buttons that use SVGs
- Fixes a regression in https://github.com/executablebooks/sphinx-book-theme/pull/771 for content width on narrow screens

Issues resolved:

- closes https://github.com/executablebooks/sphinx-book-theme/issues/746
- resolves https://github.com/executablebooks/sphinx-book-theme/issues/761
- resolves https://github.com/executablebooks/sphinx-book-theme/issues/765

I think this is ready to merge, the two failures aren't related to this PR...

- I have a PR to fix the docs audit failure: https://github.com/pydata/pydata-sphinx-theme/pull/1556
- And an issue related to the windows build failure: https://github.com/pradyunsg/sphinx-theme-builder/issues/46

### CODE REVIEW

**Comment by choldgraf** [comment]
@Gouvernathor I've got some changes in this one that are relevant to you, if you want to take a look

**Comment by Gouvernathor** [comment]
That sounds great, how can I test how it renders ?

**Comment by choldgraf** [comment]
I think for now your best bet is to look at the rendered documentation preview from this PR.

https://sphinx-book-theme--775.org.readthedocs.build/en/775/

It will be way easier to just check that out and estimate how it would look rather than to build your docs locally with this PR.

**Comment by Gouvernathor** [comment]
Thanks ! It's more than enough.
As for the background color, I would prefer the former color, `#121212`, which is [visually much darker](https://sphinx-book-theme.readthedocs.io/en/stable/) than [this new one](https://sphinx-book-theme--775.org.readthedocs.build/en/775/). Even darker would be acceptable too, for me, but a simple rollback to the previous color (which is still part of the version of book that's considered "stable") may be more acceptable for users at-large,
The "back to top" and research bar changes are great.

**Comment by choldgraf** [comment]
Fair enough - I think keeping the old background color is less messy anyway. I'd rather not change something if we don't have a clear rationale for doing so. I've reverted that back in the last commit

**Comment by choldgraf** [comment]
OK going to merge this one in as soon as the audit test is happy. I think it's a good enough improvement and is another step to unblocking folks with all the upstream updates.

**Pull request merged**
