### PR TITLE
Let's fix codecov

### PR DESCRIPTION
**Pull request by pradyunsg**
Broke in #172. Built on top of #177.

Let's see if I can figure out *why*, because `pytest` does generate the file codecov wants to use, when I run pytest locally.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
When you say coveralls, I guess you mean codecov?

**Comment by pradyunsg** [comment]
lol

**Comment by pradyunsg** [comment]
The file exists. Why is codecov not happy with it? >.<

https://github.com/executablebooks/sphinx-book-theme/pull/179/checks?check_run_id=979013832#step:6:11

**Comment by chrisjsewell** [comment]
note codecov seems to be not working in all repositories at the moment

**Comment by choldgraf** [comment]
Maybe this is a setting in codecov itself we need to change? Could it have been broken back when we renamed the org?

**Comment by chrisjsewell** [comment]
As I m motioned somewhere else, I think codecov is playing up in general in the last ~24 hours

**Comment by chrisjsewell** [comment]
The checks aren't showing up in any PRs

**Comment by pradyunsg** [comment]
So... you're saying... that I didn't break it?

\o/

**Comment by chrisjsewell** [comment]
> So... you're saying... that I didn't break it?

Oh no, I still blame you for breaking all of CodeCov 😆

**Comment by chrisjsewell** [comment]
yep codecov is reporting again on workflow re-run, you might have to push a commit to get it to show up in the checks?

**Comment by pradyunsg** [comment]
Nothing to do here, it seems. :)

**Pull request closed without merging**
