### PR TITLE
FIX: Scroll to active navigation item

### PR DESCRIPTION
**Pull request by ksuess**
Fix https://github.com/executablebooks/sphinx-book-theme/issues/608

### CODE REVIEW

**Comment by ksuess** [comment]
It would be great to have this fix merged and released before the big upgrade to current pydata-theme. @choldgraf, could you have a look?

**Review by choldgraf — APPROVED** [review]
This looks good to me - I was thinking that we should wait and see if the pydata theme upgrade fixes this, but I agree that'll be a bit of a bigger change and we might as well push out this bugfix in the meantime 👍 

- ref: https://github.com/executablebooks/sphinx-book-theme/pull/597

**Comment by ksuess** [comment]
Thank you @choldgraf for reviewing and merging. 
The upgrade to pydata-sphinx-theme~=0.10 will bring breaking changes. Maybe a 0.3.x release before this upgrade would be a good idea. What do you think?

**Comment by choldgraf** [comment]
agreed - I created an issue to cut a patch release here:

- https://github.com/executablebooks/sphinx-book-theme/issues/611

However I don't have much time for this so I welcome others to give a shot at releasing

**Pull request merged**
