### PR TITLE
⬆️ UPGRADE: Use pyScss instead of libsass

### LINKED ISSUE #195: Replace libsass with pure python implementation
I want to create a docker image based on alpine linux for sphinx and this awesome theme. Libsass package is too complicated, it must be compiled and it is too heavy (~60MB) also. Would it be possible to replace it with another written in pure python? For example https://github.com/Kronuz/pyScss?

### PR DESCRIPTION
**Pull request by hason**
Fix #195

### CODE REVIEW

**Review by chrisjsewell — APPROVED** [review]

**Comment by chrisjsewell** [comment]
Well I'm happy to merge this. @pradyunsg any objections?

**Comment by pradyunsg** [comment]
As long as pyscss is a drop-in-ish replacement to libsass in terms of syntax etc, no objections. :)

**Comment by pradyunsg** [comment]
And, thanks for checking! ^>^

**Comment by chrisjsewell** [comment]
> And, thanks for checking! ^>^

Well its always nice to be kept in the loop. Which is apparently not part of the conda-forge policy 👀 https://github.com/conda-forge/staged-recipes/pull/12511

**Comment by choldgraf** [comment]
+1 from me if it's more lightweight and the outputs are the same (which they seem to be)

**Comment by chrisjsewell** [comment]
goddamit, straight after I merge, I find out that pyScss doesn't seem to support `@use` and only the defunct `@import` https://sass-lang.com/documentation/at-rules/import

**Comment by chrisjsewell** [comment]
linking https://github.com/Kronuz/pyScss/issues/409

**Comment by chrisjsewell** [comment]
Err, I'm not sure about this compiler, now I start to see unadressed issues like this https://github.com/Kronuz/pyScss/issues/370

**Comment by chrisjsewell** [comment]
hmm, libsass doesn't see to support it either, or at least I can't get it working?
Seems strange that there's no support, when there is such a big warning sign about `@import`

**Comment by chrisjsewell** [comment]
Hmm, libsass doesn't seem to support it either? Or maybe its just me being a newb

**Comment by chrisjsewell** [comment]
it also doesn't support sourcemap generation https://github.com/Kronuz/pyScss/issues/224

**Comment by pradyunsg** [comment]
:(

Are we OK with the GitHub repository not being directly-installable?

**Comment by chrisjsewell** [comment]
This is kind of funny; I created an issue about the maintenance status https://github.com/Kronuz/pyScss/issues/410, mentioning a few PRs that had been open for months, and within a few hours 4 PRs had been merged of which I was thanked for one.

Its still an annoyance that source maps aren't available

> Are we OK with the GitHub repository not being directly-installable?

I have no strong opinions on this, I rarely install directly from a repo.
You probably know more than most if this is an issue?

**Pull request merged**
