### PR TITLE
👌 NEW: Added tag for cell-input

### PR DESCRIPTION
**Pull request by AakashGfude**
As suggested by @mmcky , we should also enable input tags to have a fixed height and scrollable, using tags.

With this PR,

```
```{code-cell} python3
---
tags: [scroll-input]
---
```

will work the same for input cells, as scroll-output was working for output cells.

If this sounds like a good addition, then we can go ahead and add it to jb docs like in this PR: https://github.com/executablebooks/jupyter-book/pull/1075/files. (although I think that these tags should be in sphinx-book-theme docs)

### CODE REVIEW

**Comment by choldgraf** [comment]
+1 from me! Wanna add some docs here and then we can tackle a PR in JB?

**Comment by AakashGfude** [comment]
@choldgraf sorry did not get you? Add docs in `sphinx-book-theme` as well?

**Comment by choldgraf** [comment]
Yep we should document in both places, since people may use this theme independent of jupyter book

**Comment by AakashGfude** [comment]
@choldgraf same goes for `scroll-output` then as well? Should I add docs for both here?

**Comment by choldgraf** [comment]
Yeah as a general rule we document everything in both spots. Longer term we could think of ways to streamline the docs but for now I think we should make sure the information is in both spots

**Comment by AakashGfude** [comment]
@choldgraf have finally added the docs 😅 . What do you think?

**Comment by choldgraf** [comment]
sorry for the slow turnaround on this - but this looks great @AakashGfude , thanks for the improvement 🎉

**Pull request merged**
