### PR TITLE
[ENH, DOC] Allow setting the `navbar_max_depth` and `collapse_navbar`

### LINKED ISSUE #603: Support additional sidebar customisation in pydata-sphinx-theme
### Context

The version of pydata-sphinx-theme version currently used, 0.8.0, has the following customisation for the sidebar:

- `show_nav_level` (sets `show_nav_level`, this theme supports it as `show_navbar_depth`)
- `navigation_depth` (sets `maxdepth`)
- `collapse_navigation` (sets `collapse`)

https://github.com/pydata/pydata-sphinx-theme/blob/v0.8.0/src/pydata_sphinx_theme/theme/pydata_sphinx_theme/_templates/sidebar-nav-bs.html

in the `main` branch the same options are available but in a new file https://github.com/pydata/pydata-sphinx-theme/blob/e2b274ae842eccdb3e6a605ce5f2389a27a43550/src/pydata_sphinx_theme/theme/pydata_sphinx_theme/layout.html

I need to customise the `maxdepth` parameter, as our help has 5 levels of help topics, and the hardcoded value currently is 4. My employer may want to set `collapse` as well. It seems to make sense to surface these configuration options together.

### Proposal

Add support for customising the  `navigation_depth` and `collapse_navigation` options.

This requires using the `theme_navigation_depth` and `theme_collapse_navigation` here https://github.com/executablebooks/sphinx-book-theme/blob/f425732ea1c2dd2f1a1ddaf0a89413a14b981baa/src/sphinx_book_theme/theme/sphinx_book_theme/components/sbt-sidebar-nav.html rather than hard coded values.

This is assuming we are happy using the same names for these option as in pydata-sphinx-theme. I suggest this is a good idea as it simplifies understanding these options when e.g. reading the pydata-sphinx-theme documentation. Although we have not done this with `show_nav_level`/`show_navbar_depth`, so maybe keeping consistant with that is more important.

### Tasks and updates

- [ ] Decide on theme option names
- [ ] Possibly add options to `theme.conf`, and support them in `sbt-sidebar-nav.html`
- [ ] Update documentation

### PR DESCRIPTION
**Pull request by gilbertbw**
I was not able to figure out how to actually build the docs I wrote for this. I have manually tested that the two new settings work for me.

As this is just exposing functionality from `pydata-sphinx-theme`, I am not sure it needs tests written?

fixes #603

### CODE REVIEW

**Review by choldgraf — APPROVED** [review]
This looks good to me - sorry for missing it before, I think it's OK to avoid testing since we are just inheriting the feature from the pydata theme, as you mention!

**Comment by choldgraf** [comment]
@gilbertbw I tried pushing to your branch to fix the merge conflict but got access denied - can you run a merge commit from `master` and then we can merge?

**Comment by choldgraf** [comment]
another ping...

**Comment by gilbertbw** [comment]
Sorry, I missed the notifications about this. I have merged in master as requested.

**Comment by Maetveis** [comment]
Hi, @choldgraf can I help somehow getting this merged? We'd like to use this option for the [ROCm documentation](https://rocm.docs.amd.com) (https://github.com/RadeonOpenCompute/rocm-docs-core/issues/413).

**Comment by Maetveis** [comment]
I rebased the branch to current master, its available here: https://github.com/StreamHPC/sphinx-book-theme/tree/gbw-additional-theme-customisation. Should I make a PR?

**Comment by choldgraf** [comment]
@Maetveis go for

**Pull request merged**
