### PR TITLE
🐛 FIX: :align: for image directive

### PR DESCRIPTION
**Pull request by najuzilu**
This PR fixes the align option for image directives. I have set the default align behavior to center.

### CODE REVIEW

**Comment by richardliaw** [comment]
This would be awesome! Currently trying to port my project to this theme, but running into the issue where images aren't being centered properly.

**Comment by choldgraf** [comment]
nice! is there someplace in the docs where we show off how people can get this to work, so we confirm that it behaves as expected?

**Comment by pradyunsg** [comment]
> is there someplace in the docs where we show off how people can get this to work, so we confirm that it behaves as expected?

https://sphinx-book-theme.readthedocs.io/en/latest/reference/demo.html#images-figures?

**Comment by choldgraf** [comment]
Ya but since the default is now center, the page just shows the same alignment 3 times

https://sphinx-book-theme--198.org.readthedocs.build/en/198/reference/demo.html#images-figures

**Comment by najuzilu** [comment]
This documentation should help clarify and test the behavior: https://sphinx-book-theme--198.org.readthedocs.build/en/198/reference/demo.html#images.
FYI, I included a couple `<br/>`s to make the documentation look nicer but would be happy to remove them if you think that's too much.

**Comment by choldgraf** [comment]
perfect! thanks so much @najuzilu :-)

**Pull request merged**
