### PR TITLE
🔧 MAINT: Loosen importlib-resources pin

### PR DESCRIPTION
**Pull request by bollwyvl**
This is another solveability experiment, from https://github.com/conda-forge/sphinx-book-theme-feedstock/pull/5.

See also:
- https://github.com/executablebooks/jupyter-book/pull/1221

### CODE REVIEW

**Comment by choldgraf** [comment]
@bollwyvl can you give some context for this?

**Comment by bollwyvl** [comment]
Since a lot of folk will expect to be able to install downstreams of this, e.g. `juptyer-book` _next to their code_, these kinds of tight pins will introduce all kinds of extremely mysterious issues.

A pin of `~=3.0.0` (translating to `>=3.0.0,<3.1`) means _exactly one version, ever_ can be installed, as it's _highly_ unlikely the upstream will publish `3.0.x` (they're already on `3.7.0`). It's unlikely there will be bug fixen, etc.

**Comment by chrisjsewell** [comment]
Yeh fair, this isn’t problem to merge. It’s only anyway required for python 3.6 (part of core after that) and python 3.6 will be end-of-life at the end of this year

**Comment by choldgraf** [comment]
I'm not sure I quite understand the implications but trust both of you two than I do myself haha. The error is the sphinxcontrib-bibtex bug, not related to this, so I'm gonna merge!

@chrisjsewell is this a change that we should implement throughout the EBP repos?

**Comment by chrisjsewell** [comment]
> is this a change that we should implement throughout the EBP repos?

well as mentioned, it is an issue that will "fix itself" as people move to using python >3.6, so its not really a priority

**Comment by choldgraf** [comment]
ah I see so once we drop support for 3.6 then this will no longer be an issue at all

**Pull request merged**
