### PR TITLE
MAINT: Update CSS for external packages and remove redundant code

### LINKED ISSUE #468: Get our lighthouse scores to "good" in relevant categories
### Description

In #467 we've added an audit with Lighthouse that will help catch some major regressions in performance, accessibility, etc. The scores for pass/fail are lower than ideal.  We should make the necessary changes to get our lighthouse score up to some minimal threshold.

Deciding on a threshold is somewhat arbitrary, but according to [this guide](https://web.dev/performance-scoring/#color-coding), 90 is considered "good" in a category. To that extent, I think our goal should be to achieve a score of 90 in the "accessibility", "performance", and "best practices" categories.

### Implementation guide

- Some of the scores might be hit by dependencies of this theme, and we could look into making improvements there as well.
- We should consider adding one of the heavier pages (e.g. the notebooks page?) if we want to push this further

### PR DESCRIPTION
**Pull request by choldgraf**
This PR does a few follow-ups to #471 , it:

- Updates some CSS that regressed in #471 
- Updates some of our regression tests so that they're more reliable and don't depend on multiple Sphinx versions (supercedes https://github.com/executablebooks/sphinx-book-theme/pull/466)
- Updates to the latest pydata sphinx theme
- Re-factors our sidebar navigation logic a bit to use less custom python, and to not require a second parse with beautifulsoup

# Todo

- [x] Everything in #476   
      closes https://github.com/executablebooks/sphinx-book-theme/issues/476
- [x] Figure out why the pydata theme 0.8 breaks the column width for bootstrap, see `content-blocks` for ex. 
- [x] Fix safari bug: 
      closes https://github.com/executablebooks/sphinx-book-theme/issues/477 
- [x] See if our accessibility scores improved with the downstream updates.
      closes #468

### CODE REVIEW

**Comment by choldgraf** [comment]
cc @mathbunnyru - I think this fixes the safari fullscreen bug. Wanna try it at: https://sphinx-book-theme--478.org.readthedocs.build/en/478/ ?

**Comment by mathbunnyru** [comment]
@choldgraf it half-works :)
So, it goes to the fullscreen, when I press the button in Safari.
But when I press it again, it doesn't go to normal mode and stays full screen (it works well in Chrome).

**Comment by choldgraf** [comment]
ok @mathbunnyru try again!

**Comment by mathbunnyru** [comment]
Seems to work now, thanks!

**Comment by choldgraf** [comment]
OK merging this one in as the next step towards our CSS refactor!

**Pull request merged**
