### PR TITLE
♻️ REFACTOR: Added scroll-output tag style

### PR DESCRIPTION
**Pull request by AakashGfude**
As resolve for this discussion https://github.com/executablebooks/meta/discussions/173 

Once this gets merged and a new version is released. We can update the docs https://github.com/executablebooks/jupyter-book/pull/1075 . Will make a new PR for updating the docs as https://github.com/executablebooks/jupyter-book/pull/1075 should be merged soon.

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AakashGfude I will also update `sphinx-tomyst` to use this tag by default.

**Comment by AakashGfude** [comment]
@mmcky , I will add the style to `quantecon-book-theme` as well.

**Comment by mmcky** [comment]
@choldgraf I think this looks ready to go.

**Comment by choldgraf** [comment]
nice - thanks @AakashGfude !!

**Pull request merged**
