### PR TITLE
Sphinx 7 support

### PR DESCRIPTION
**Pull request by LecrisUT**
Cannot install testing suite because of dependency hell. Any advice on this? See my fork PR https://github.com/LecrisUT/sphinx-book-theme/pull/1. Any ways to drop `myst-nb` and `sphinx_thebe` testing requirement? It is hell to try and detangle their testing requirements.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
myst-nb actually supports sphinx 7, we simply need the maintainers to tag a new release...

**Comment by LecrisUT** [comment]
Indeed, you can see the author there :D https://github.com/executablebooks/MyST-NB/pull/524. Right now Sphinx-thebe is the hold-up https://github.com/executablebooks/sphinx-thebe/pull/67. I don't know how to make a good testing suite there to decouple it from `sphinx-book-theme` which otherwise creates a cyclic dependency issue.

**Comment by Eutropios** [comment]
Is there any word on this being resolved?

**Comment by LecrisUT** [comment]
If we can yolo both this and sphinx-thebe to get rid of the silly cyclic dependency the CIs will then be back running properly and we can pick up from there. @choldgraf any thoughts?

**Comment by choldgraf** [comment]
I've just made a release of sphinx-thebe to unblock this on the version pinning issue:

https://github.com/executablebooks/sphinx-thebe/releases/tag/v0.3.0

**Comment by LecrisUT** [comment]
Ok, I'll get the CIs back and running, and mark some of them as experimental if needed, then we can open new PRs to de-mark the experimental. Sounds good?

Btw, what are your thoughts on making some of the CIs more templetize (or even importable) to ve consistent across each other. I can write a mock-up over here and then have them moved to a new repo maintained more regularly under executablebooks?

**Comment by choldgraf** [comment]
For now I'd recommend just taking the minimal actions and complexity needed to support the latest Sphinx and be reasonably certain we aren't introducing obvious regressions. Improving broader infrastructure sounds good but like it might add a lot of extra work to getting this unblocked. Right now we are extremely heavily limited in maintainer capacity...

**Comment by LecrisUT** [comment]
@choldgraf Ok, for now here is some minimal updates, with a few fixed pytests. The currently failing ones seem trivial, just need to update the regression test files for different versions.

The windows CI does not work in how I wrote it. Can you help with that? I will mark it experimental for the time-being

**Comment by LecrisUT** [comment]
All ready on this PR, might add some CI improvements in another PR. The only one I don't understand is the windows one :(. Should be fine for at least a pre-release tag, since `myst-nb` is also gated as pre-release?

**Review by choldgraf — APPROVED** [review]
Looks good to me - let's merge it in and iterate on PRs from there. I'm not sure what's up with the Windows bug either, but I don't _think_ it's related to this PR. Thanks for making this effort!

**Comment by Eutropios** [comment]
Thank you both for the hard work! @LecrisUT @choldgraf

**Pull request merged**
