### PR TITLE
✨ NEW: Add a shadow to topbar, on scroll

### LINKED ISSUE #153: Add a shadow to the top bar on scroll
**Is your feature request related to a problem? Please describe.**

Content at the top of the page gets cropped, seemingly for no reason.

**Describe the solution you'd like**

A shadow underneath the top bar would make it easier to perceive that there is an element that's supposed to be on top, making it clearer why content is getting cropped (there's something above it!).

**Describe alternatives you've considered**

None.

**Additional context**

See https://squidfunk.github.io/mkdocs-material/getting-started/ for a decent+subtle implementation of this.

### PR DESCRIPTION
**Pull request by pradyunsg**
Fixes #153

### CODE REVIEW

**Comment by choldgraf** [comment]
Nice! I think this is a nice step. Do you think there is a way that we could make the shadow a bit softer? It seems like it "jumps out" at me on the page, though that might just be because I am used to no shadow and I would get used to it quickly. What do you think?

**Comment by pradyunsg** [comment]
Done!

Before:

Screenshot 2020-11-10 at 4 19 13 AM

After:

Screenshot 2020-11-10 at 4 18 39 AM

**Comment by choldgraf** [comment]
This is better! I am happy with this level of boldness :-)

One other quick thought, and maybe this is just me being OCD, but it's kinda bugging me that there is just a _tiny_ bit of space on the left where the shadow doesn't extend, but before we hit the sidebar:

image

Is that something easily fixable? I don't think it's a dealbreaker

**Comment by pradyunsg** [comment]
> Is that something easily fixable? I don't think it's a dealbreaker

It's tricky with the way that the elements are organised. Maybe someone smart can figure it out, but for now I've set the box-shadow to never overflow over the left/right by setting the box's size to be `-6px` -- that's what's causing this behavior that you're seeing.

I can tell you it bothers me as much as it bothers you, but "perfect is the enemy of good" -- IOW, I didn't want to spend an hour fighting with the browser. :)

**Comment by choldgraf** [comment]
Agree 💯, was just mentioning it in case it was an easy fix. I'm +1 on this once the merge conflict is resolved.

**Comment by pradyunsg** [comment]
If someone else could do the rebase/merge, that'd be great! :)

I don't think I'll be able to get to this at least for a few days.

**Comment by choldgraf** [comment]
this looks great @pradyunsg - thanks for adding this, I quite like it! 🎉

**Comment by pradyunsg** [comment]
Yay! I’m glad!

**Pull request merged**
