### PR TITLE
FIX: Scroll padding on top for anchor links

### PR DESCRIPTION
**Pull request by choldgraf**
- closes https://github.com/executablebooks/sphinx-book-theme/issues/667

The failing test is a lighthouse performance check, which is notoriously flaky and I think can be ignored

### CODE REVIEW

**Comment by choldgraf** [comment]
This one is a minor bugfix, so will self-merge if the tests and UX works as expected.

**Comment by choldgraf** [comment]
Hmmm good point - it is a bit tricky to get just right, because if the top padding is too small then we will accidentally highlight the wrong section and the original problem will come back. I reduced the padding at the top in the latest commit to try to strike a balance. WDYT?

**Comment by mathbunnyru** [comment]
I think it looks better now, but I still see the text from the previous part. I guess it's impossible to have both things.
Screenshot 2023-01-05 at 19 16 40

**Comment by choldgraf** [comment]
OK how's this? It means that if we have two headers directly after one another, we might accidentally highlight the second, but maybe that's not such a big deal and also not common.

**Comment by mathbunnyru** [comment]
Now it looks great to me 👍

**Pull request merged**
