### PR TITLE
MAINT: Fix tests with updated upstream

### PR DESCRIPTION
**Pull request by choldgraf**
This updates our regression tests so that they pass. Will look at the diff and see if anything meaningful has changed. If not then I'll just merge so that we can inspect the other PRs more effectively.

### CODE REVIEW

**Comment by choldgraf** [comment]
This all looks to be cosmetic and based on changes in the pydata theme, so let's tackle any UI changes in subsequent PRs and merge this one if tests are happy.

**Comment by choldgraf** [comment]
@agoose77 any idea what the broken RTD error is? Here's the relevant bit, it seems to be choking when it tries to install pandas:

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      /tmp/pip-install-6ricahb1/pandas_c91e810c40ee4cf7a965f5b8bf5a9150/setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      /home/docs/checkouts/readthedocs.org/user_builds/sphinx-book-theme/envs/766/lib/python3.7/site-packages/setuptools/__init__.py:84: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      error in pandas setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          pytz >= 2011k
               ~~~~~~~^
      [end of output]
```

**Comment by agoose77** [comment]
@choldgraf [23917da](https://github.com/executablebooks/sphinx-book-theme/pull/766/commits/23917daa04dfda00fece7f2bbb9ac52e2e71a6a5) should do it! Not sure why the default is 3.7, but bumped the RTD Python version to 3.10

**Comment by choldgraf** [comment]
@agoose77 ah shit we just clobbered each other. I didn't realize you had pushed to this branch, sorry about that. I just updated to 3.10 in Sphinx and fixed some bugs that I think were in the pinned dependencies for our docs build (that I think no longer needed pinning). Let's see if that makes things happy.

**Comment by choldgraf** [comment]
OK readthedocs has some seriously wonky python version action going on. They only seem to support up to 3.8, and don't install it by default, even though one of our dependencies now requires a minimum of 3.8. So I really hope they resolve that one soon!

**Comment by choldgraf** [comment]
Well @agoose77 I'm back to the `install_requires` bug. If you wanna work your magic and fix it again that would be awesome, I promise to check and not to clobber your commit this time!

**Comment by choldgraf** [comment]
@agoose77 ahh I see, new config structure. OK I'm stepping away from the computer for a bit so feel free to merge and iterate if you like, otherwise I'll take a look when I get home

**Comment by choldgraf** [comment]
Woot tests are happy, let's merge it and see how it impacts all of the other PRs :-) thanks @agoose77 for your help!

**Comment by choldgraf** [comment]
oh wow I should overwrite `git push -f` with that haha

**Pull request merged**
