### PR TITLE
replace 'Contents' with 'On this page'

### LINKED ISSUE #290: Single content option
I am using this theme via jupyterbook here: https://vita-epfl.github.io/openpifpaf/dev/intro.html

One feedback that I got is that the two navigation bars on the left and right are confusing and whether it would be possible to just have a single one.

Alternatively, it would be nice to change or customize the title of the right navigation bar: "Contents" seems more appropriate for the left navigation bar. I would like to name the right one "On this page".

### PR DESCRIPTION
**Pull request by svenkreiss**
Fixes #290.

### CODE REVIEW

**Comment by choldgraf** [comment]
Hmmm I think that rather than changing this (which would also change it for everybody else), I’d recommend making this configurable. We could add a config value to the theme options that would override the default title for the the within page toc. Then you could override as you wish. Want to give that a shot?

**Comment by chrisjsewell** [comment]
I would point out that we literally already changed this in the opposite direction: https://github.com/executablebooks/sphinx-book-theme/issues/145

**Comment by svenkreiss** [comment]
I wasn't aware of #145. Obviously I disagree with the outcome of that discussion :)

**Comment by choldgraf** [comment]
OK - I opened up #297 to track making this configurable, so going to close this PR. Thanks @svenkreiss for bringing it up!

**Pull request closed without merging**
