### PR TITLE
FIX: Translation support and add new translations

### PR DESCRIPTION
**Pull request by AakashGfude**
- [x] fix `_compile_translations.py` , so that .mo files are present in build folder
- [ ] add missing translations

fixes https://github.com/executablebooks/sphinx-book-theme/issues/584

### CODE REVIEW

**Comment by AakashGfude** [comment]
@choldgraf it seems I can only translate to 9 languages from smodin. Do you have a premium account? As it seems other words have translations in more languages.

**Comment by choldgraf** [comment]
Let's just go with the 9 languages - this is just a start anyway, I think that it will likely require manual updates for many languages anyway since automatic translating is likely to so things slightly incorrectly

**Comment by AakashGfude** [comment]
ooh okay cool. I reckon we need to find words manually of what we want to update. Some words already found are:- 
`Last updated on` and `By` as mentioned in the issue https://github.com/executablebooks/sphinx-book-theme/issues/584 .  So, I will just go with that for now.

**Comment by choldgraf** [comment]
Yeah that makes sense - we can do the best we can now, and if we miss something we can always improve it in a future PR !

**Comment by choldgraf** [comment]
By the way, do you know how to handle translation strings when there is a word that isn't supposed to be translated? Eg "edit on GitHub" - we want "GitHub" to be part of the phrase (so that for example German speakers see it at the beginning of the phrase instead of the end), but it isn't translatable. I think there are guidelines for how to handle this but I don't know what they are

**Comment by AakashGfude** [comment]
By the way, `Last updated on` and `By` are already here https://github.com/executablebooks/sphinx-book-theme/tree/master/src/sphinx_book_theme/assets/translations/jsons . So, I guess we don't need to add any translations at the moment?

**Comment by choldgraf** [comment]
Ah nice - so we don't need to change anything for now? If that's the case I think we should just merge this and cut a release candidate

**Comment by AakashGfude** [comment]
> Ah nice - so we don't need to change anything for now?
Seems like it. But I don't know why it was not working in the first place. Because of lack of `.mo` files?

**Comment by choldgraf** [comment]
Yes without those files present six
Sphinx cannot generate any translations

**Pull request merged**
