### PR TITLE
UPGRADE/BREAKING: PyData v0.13 and HTML refactoring

### LINKED ISSUE #265: Add a dark mode
### Description

Many themes have at least two options for their CSS: light and dark mode. Dark mode is a common feature to help reduce strain on the eyes. We should offer something like this in the sphinx-book-theme, perhaps as a toggle.

Dark modes can help people parse some content more easily, so this is partially an accessibility issue.
Maybe others (@pradyunsg ?) have experience w/ this too.

Here's a blog post that describes how dark modes can work w/ minimal CSS changes: https://prudhvirampey.com/blog/colours/jekyll/css/fastpages/2020/10/30/hello-dark-mode.html

Another option would be to fix this in the pydata theme (in fact, @bollwyvl already has a shot at implementation). This would solve the problem for both themes! Here's a link to the issue: https://github.com/pydata/pydata-sphinx-theme/issues/458

### Actions

Here are the actions needed to do this:

- [x] pydata theme release is made: https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.9.0
- [x] update the dependency in the book theme
- [x] https://github.com/executablebooks/sphinx-book-theme/pull/597
- [ ] https://github.com/executablebooks/sphinx-book-theme/pull/640
- [ ] Add support for a dark mode button
- [ ] Confirm there are no extra places to update our CSS for dark mode
- [ ] merge that in here and make a release of the book theme

### PR DESCRIPTION
**Pull request by choldgraf**
This brings in several more updates for the PyData theme 0.13. It also adds support for several features that folks have requested.

- Adds two more buttons to our header buttons (theme and search). This is starting to get cluttered and we may want to move some stuff to the sidebar, but for now I'm just adding to this list so that we don't clutter up this PR too much.
- We now support dark mode! closes #265 
- We now use the "search icon" for searching, same as the pydata theme
- I fixed up a few CSS rules that were producing wonky behavior.
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/678
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/681
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/638
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/625
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/619
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/565
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/563
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/182
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/334
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/332
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/325
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/169
	- closes https://github.com/executablebooks/sphinx-book-theme/issues/248

That's pretty much it so far! @mmcky or @AakashGfude can you find anything else we need to change?

### To do

- [x] Unpin the pydata theme to the latest release when v0.13 is out

### CODE REVIEW

**Comment by choldgraf** [comment]
Alright I've pinned us to the next pydata _pre-release_, so this should let us pull from PyPI. I've also made several updates to the theme based on the latest changes in PyData, and re-worked the documentation a bit to be easier to parse.

I think that this PR is too gigantic to be reviewed piece by piece, so I suggest that we merge it and focus on making iterative improvements moving forward.

Let's see how the tests go, and if they pass I intend to merge this and then cut a pre-release once @AakashGfude fixes up #584 . Then we can have another testing phase for people to provide feedback before a full release (and in the meantime, I think pydata will make a new version release too).

**Comment by choldgraf** [comment]
OK tests are happy, so I'll merge this one and update your branch @AakashGfude

**Comment by consideRatio** [comment]
Wieeeeeee!!! Amazing work! Super excited to see soo many issues resolve :)

I thought all these notifications of closed issues maybe was a mistake as they closed the very same minute, but wow - its because of this PR! I've never seen a PR resolve soo many issues in one go!! @choldgraf you hold the record now :D

:1st_place_medal: :tada: :sunflower: :heart:

**Comment by choldgraf** [comment]
Haha to be fair many of these were inherited from the pydata theme, which has had a lot of work from many people over the months

**Comment by James11222** [comment]
Sorry I'm a little bit of a Github novice and don't really know how all of this works. So does this mean I can now toggle dark mode in Jupyter books? Or is there still a little bit of time we have to wait for a new version on the website or something?

**Comment by choldgraf** [comment]
It will be possible soon! We must first "make a release of this theme", and then in Jupyter book we must update the version and then make a release there too. Then it'll be available for jupyter book users 👍

**Pull request merged**
